                <div class="col s12 m3 left">
                </div>
            </div>
        </div>
        <div class="footer z-depth-3">
            <footer class="page-footer light-blue darken-1">
                <div class="container">
                    <div class="row">
                        <div class="col l6 s12">
                            <h5 class="white-text">About AutoVM</h5>
                            <p class="grey-text text-lighten-4">AutoVM is an open source platform to manage virtual machines(VM) on the VMware ESXI virtualization which allows the VPS providers to manage full automation of support and sales process.</p>
                        </div>
                        <div class="col l4 offset-l2 s12">
                            <h5 class="white-text">Useful Links</h5>
                            <ul>
                                <li><a class="grey-text text-lighten-3" href="http://autovm.net/en/lab.php" target="_blank">Lab</a></li>                                
								<li><a class="grey-text text-lighten-3" href="http://wiki.autovm.net" target="_blank">Wiki</a></li>
                                <li><a class="grey-text text-lighten-3" href="http://autovm.net/en/about.html" target="_blank">About</a></li>
                                <li><a class="grey-text text-lighten-3" href="http://autovm.net/en/contact.html" target="_blank">Contact</a>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="footer-copyright">
                    <div class="container">
                        © 2018 Created and designed by AutoVM, all rights reserved.
                        <a class="grey-text text-lighten-4 right" href="http://autovm.net/en" target="_blank">AutoVM</a>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>