<div class="col s12 m3">
    <div class="card install-process">
        <?php if($step == 1) {?>
        <p class="blue white-text">
        <?php } else {?>
        <p>
        <?php }?>
            <i class="left material-icons">keyboard_arrow_right</i> Welcome
        </p>
        <div class="divider"></div>
        
        <?php if($step == 2) {?>
        <p class="blue white-text">
        <?php } else {?>
        <p>
        <?php }?>
            <i class="left material-icons">keyboard_arrow_right</i> Installation
        </p>
        <div class="divider"></div>
        
        <?php if($step == 3) {?>
        <p class="blue white-text">
        <?php } else {?>
        <p>
        <?php }?>
            <i class="left material-icons">keyboard_arrow_right</i> Complete
        </p>
    </div>
</div>